spring.application.name=demo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/companeges
spring.datasource.username=juvino
spring.datasource.password=juvino123
spring.jpa.hibernate.ddl-auto=update

