package com.companages.service;
import com.companages.dto.AuthDtos.*; import com.companages.entity.*; import com.companages.exception.*; import com.companages.repository.*; import com.companages.security.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.authentication.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant;
@Service public class AuthService {
 private final UserRepository users; private final RefreshTokenRepository refreshTokens; private final PasswordResetTokenRepository resetTokens; private final PasswordEncoder encoder; private final AuthenticationManager authentication; private final JwtService jwt; private final OpaqueTokenService opaque; private final CurrentUserService current; private final MailService mail; private final long refreshExpiration; private final String frontendUrl;
 public AuthService(UserRepository u,RefreshTokenRepository rt,PasswordResetTokenRepository pr,PasswordEncoder e,AuthenticationManager a,JwtService j,OpaqueTokenService o,CurrentUserService c,MailService m,@Value("${app.jwt.refresh-expiration-ms}")long re,@Value("${app.frontend-url}")String url){users=u;refreshTokens=rt;resetTokens=pr;encoder=e;authentication=a;jwt=j;opaque=o;current=c;mail=m;refreshExpiration=re;frontendUrl=url;}
 @Transactional public AuthResponse register(RegisterRequest r){String email=r.email().trim().toLowerCase();if(users.existsByEmailIgnoreCase(email))throw new EmailAlreadyExistsException();User u=new User();u.setName(r.name().trim());u.setEmail(email);u.setPassword(encoder.encode(r.password()));return issue(users.save(u));}
 @Transactional public AuthResponse login(LoginRequest r){authentication.authenticate(new UsernamePasswordAuthenticationToken(r.email(),r.password()));return issue(users.findByEmailIgnoreCase(r.email()).orElseThrow());}
 @Transactional public AuthResponse refresh(RefreshRequest r){RefreshToken stored=refreshTokens.findByTokenHash(opaque.hash(r.refreshToken())).orElseThrow(()->new InvalidTokenException("Invalid refresh token"));if(!stored.active())throw new InvalidTokenException("Refresh token is expired or revoked");stored.setRevokedAt(Instant.now());return issue(stored.getUser());}
 @Transactional public void logout(LogoutRequest r){refreshTokens.findByTokenHash(opaque.hash(r.refreshToken())).ifPresent(t->t.setRevokedAt(Instant.now()));}
 @Transactional public void forgotPassword(ForgotPasswordRequest r){users.findByEmailIgnoreCase(r.email()).ifPresent(u->{String raw=opaque.create();PasswordResetToken t=new PasswordResetToken();t.setUser(u);t.setTokenHash(opaque.hash(raw));t.setExpiresAt(Instant.now().plusSeconds(3600));resetTokens.save(t);mail.send(u.getEmail(),"Reset your Companages password","Open this link within one hour: "+frontendUrl+"/reset-password?token="+raw);});}
 @Transactional public void resetPassword(ResetPasswordRequest r){PasswordResetToken t=resetTokens.findByTokenHash(opaque.hash(r.token())).orElseThrow(()->new InvalidTokenException("Invalid reset token"));if(!t.active())throw new InvalidTokenException("Reset token is expired or already used");t.getUser().setPassword(encoder.encode(r.newPassword()));t.setUsedAt(Instant.now());refreshTokens.revokeAll(t.getUser().getId(),Instant.now());}
 @Transactional public void changePassword(ChangePasswordRequest r){User u=current.get();if(!encoder.matches(r.currentPassword(),u.getPassword()))throw new BadCredentialsException("Invalid current password");u.setPassword(encoder.encode(r.newPassword()));refreshTokens.revokeAll(u.getId(),Instant.now());}
 @Transactional public UserResponse updateProfile(UpdateProfileRequest r){User u=current.get();u.setName(r.name().trim());u.setAvatarUrl(r.avatarUrl());u.setPhone(r.phone());u.setBio(r.bio());return Mappers.user(u);}
 public UserResponse me(){return Mappers.user(current.get());}
 private AuthResponse issue(User u){String access=jwt.generate(u.getEmail()),raw=opaque.create();RefreshToken token=new RefreshToken();token.setUser(u);token.setTokenHash(opaque.hash(raw));token.setExpiresAt(Instant.now().plusMillis(refreshExpiration));refreshTokens.save(token);return new AuthResponse(access,access,raw,jwt.expirationMillis(),Mappers.user(u));}
}
