package com.companages.service;
import com.companages.dto.*; import com.companages.dto.InvitationDtos.*; import com.companages.entity.*; import com.companages.exception.*; import com.companages.repository.*; import com.companages.security.OpaqueTokenService; import jakarta.persistence.criteria.Predicate; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.ArrayList;
@Service public class InvitationService { private final InvitationRepository invitations; private final MemberRepository members; private final UserRepository users; private final OrganizationAccessService access; private final CurrentUserService current; private final OpaqueTokenService tokens; private final MailService mail; private final ActivityService activities; private final NotificationService notifications; private final String frontendUrl;
 public InvitationService(InvitationRepository i,MemberRepository m,UserRepository u,OrganizationAccessService a,CurrentUserService c,OpaqueTokenService t,MailService mail,ActivityService l,NotificationService n,@Value("${app.frontend-url}")String url){invitations=i;members=m;users=u;access=a;current=c;tokens=t;this.mail=mail;activities=l;notifications=n;frontendUrl=url;}
 @Transactional public Response send(Long oid,InviteRequest r){Member actor=access.requireAdmin(oid);if(r.role()==AccessRole.OWNER)throw new BusinessException("Owner access cannot be granted by invitation");String email=r.email().trim().toLowerCase();users.findByEmailIgnoreCase(email).ifPresent(u->{if(members.existsByOrganizationIdAndUserId(oid,u.getId()))throw new BusinessException("This user is already a member");});if(invitations.existsByOrganizationIdAndEmailIgnoreCaseAndStatus(oid,email,InvitationStatus.PENDING))throw new BusinessException("A pending invitation already exists");Invitation i=new Invitation();i.setOrganization(actor.getOrganization());i.setEmail(email);i.setRole(r.role());i.setInvitedBy(current.get());i.setExpiresAt(Instant.now().plus(Duration.ofDays(7)));String raw=tokens.create();i.setTokenHash(tokens.hash(raw));i=invitations.save(i);sendEmail(i,raw);users.findByEmailIgnoreCase(email).ifPresent(u->notifications.create(u,actor.getOrganization(),"INVITATION","Invitation to "+actor.getOrganization().getName(),"You received a new organization invitation.","/notifications"));if(actor.getUser()!=null)notifications.create(actor.getUser(),actor.getOrganization(),"INVITATION_SENT","Invitation sent","An invitation was sent to "+email+".","/invitations");activities.record(actor.getOrganization(),ActivityAction.INVITATION_SENT,"Invitation",i.getId(),email);return map(i);}
 @Transactional(readOnly=true) public PageResponse<Response> list(Long oid,String search,InvitationStatus status,Pageable p){access.requireAdmin(oid);String term=search==null||search.isBlank()?null:search.trim().toLowerCase();Specification<Invitation> spec=(root,query,cb)->{var predicates=new ArrayList<Predicate>();predicates.add(cb.equal(root.get("organization").get("id"),oid));if(term!=null)predicates.add(cb.like(cb.lower(root.get("email")),"%"+term+"%"));if(status!=null)predicates.add(cb.equal(root.get("status"),status));return cb.and(predicates.toArray(Predicate[]::new));};return PageResponse.from(invitations.findAll(spec,p),this::map);}
 @Transactional(readOnly=true) public Response validate(String raw){Invitation i=valid(raw);return map(i);}
 @Transactional public Response accept(AcceptRequest r){Invitation i=valid(r.token());User user=current.get();if(!user.getEmail().equalsIgnoreCase(i.getEmail()))throw new ForbiddenException("This invitation belongs to another email address");if(!members.existsByOrganizationIdAndUserId(i.getOrganization().getId(),user.getId())){Member m=new Member();m.setOrganization(i.getOrganization());m.setUser(user);m.setName(user.getName());m.setEmail(user.getEmail());m.setAccessRole(i.getRole());m.setStatus(RecordStatus.ACTIVE);m.setJoinedAt(LocalDate.now());members.save(m);}i.setStatus(InvitationStatus.ACCEPTED);i.setAcceptedAt(Instant.now());activities.record(i.getOrganization(),ActivityAction.INVITATION_ACCEPTED,"Invitation",i.getId(),user.getName());notifications.create(user,i.getOrganization(),"INVITATION_ACCEPTED","Welcome to "+i.getOrganization().getName(),"Your invitation was accepted.","/dashboard");return map(i);}
 @Transactional public void cancel(Long oid,Long id){access.requireAdmin(oid);Invitation i=require(oid,id);i.setStatus(InvitationStatus.CANCELLED);}
 @Transactional public Response resend(Long oid,Long id){access.requireAdmin(oid);Invitation i=require(oid,id);if(i.getStatus()==InvitationStatus.ACCEPTED)throw new BusinessException("Accepted invitations cannot be resent");String raw=tokens.create();i.setTokenHash(tokens.hash(raw));i.setExpiresAt(Instant.now().plus(Duration.ofDays(7)));i.setStatus(InvitationStatus.PENDING);sendEmail(i,raw);return map(i);}
 private Invitation valid(String raw){Invitation i=invitations.findByTokenHash(tokens.hash(raw)).orElseThrow(()->new InvalidTokenException("Invalid invitation token"));if(i.getStatus()!=InvitationStatus.PENDING||i.getExpiresAt().isBefore(Instant.now())){if(i.getStatus()==InvitationStatus.PENDING)i.setStatus(InvitationStatus.EXPIRED);throw new InvalidTokenException("Invitation is expired or unavailable");}return i;} private Invitation require(Long oid,Long id){return invitations.findByIdAndOrganizationId(id,oid).orElseThrow(()->new ResourceNotFoundException("Invitation not found"));} private void sendEmail(Invitation i,String raw){mail.send(i.getEmail(),"Invitation to "+i.getOrganization().getName(),"Open this link to join: "+frontendUrl+"/invitations/accept?token="+raw);} private Response map(Invitation i){return new Response(i.getId(),i.getOrganization().getId(),i.getOrganization().getName(),i.getEmail(),i.getRole(),i.getStatus(),i.getExpiresAt(),i.getAcceptedAt(),i.getCreatedAt());}
}
