package com.companages.service;
import com.companages.dto.*; import com.companages.dto.MemberDtos.*; import com.companages.entity.*; import com.companages.exception.*; import com.companages.repository.*; import jakarta.persistence.criteria.Predicate; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*;
@Service public class MemberService {
 private final MemberRepository members; private final PositionRepository positions; private final TeamRepository teams; private final OrganizationAccessService access; private final ActivityService activities; private final NotificationService notifications;
 public MemberService(MemberRepository m,PositionRepository p,TeamRepository t,OrganizationAccessService a,ActivityService l,NotificationService n){members=m;positions=p;teams=t;access=a;activities=l;notifications=n;}
 @Transactional public Response create(Long oid,Request r){Member actor=access.requireAdmin(oid);Member m=new Member();m.setOrganization(actor.getOrganization());m.setAccessRole(r.accessRole()==null?AccessRole.MEMBER:allowedRole(actor,r.accessRole()));m.setJoinedAt(r.joinedAt()==null?LocalDate.now():r.joinedAt());apply(m,r,oid);m=members.save(m);activities.record(actor.getOrganization(),ActivityAction.MEMBER_ADDED,"Member",m.getId(),m.getName());return Mappers.member(m);}
 @Transactional(readOnly=true) public List<Response> list(Long oid){access.requireMember(oid);return members.findAllByOrganizationIdOrderByName(oid).stream().map(Mappers::member).toList();}
 @Transactional(readOnly=true) public PageResponse<Response> search(Long oid,String search,Long teamId,RecordStatus status,Pageable pageable){access.requireMember(oid);String term=blank(search);Specification<Member> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.equal(root.get("organization").get("id"),oid));if(term!=null){String like="%"+term.toLowerCase()+"%";p.add(cb.or(cb.like(cb.lower(root.get("name")),like),cb.like(cb.lower(root.get("email")),like)));}if(teamId!=null)p.add(cb.equal(root.get("team").get("id"),teamId));if(status!=null)p.add(cb.equal(root.get("status"),status));return cb.and(p.toArray(Predicate[]::new));};return PageResponse.from(members.findAll(spec,pageable),Mappers::member);}
 @Transactional(readOnly=true) public Response get(Long oid,Long id){access.requireMember(oid);return Mappers.member(require(oid,id));}
 @Transactional public Response update(Long oid,Long id,Request r){Member actor=access.requireManager(oid);Member m=require(oid,id);ensureManagerScope(actor,m);AccessRole oldRole=m.getAccessRole();Long oldManager=m.getManager()==null?null:m.getManager().getId();Long oldTeam=m.getTeam()==null?null:m.getTeam().getId();Long oldPosition=m.getPosition()==null?null:m.getPosition().getId();apply(m,r,oid);if(r.accessRole()!=null){if(actor.getAccessRole()==AccessRole.MANAGER&&r.accessRole()!=oldRole)throw new ForbiddenException("Managers cannot change access roles");m.setAccessRole(allowedRole(actor,r.accessRole()));}activities.record(actor.getOrganization(),ActivityAction.MEMBER_UPDATED,"Member",m.getId(),m.getName());if(oldRole!=m.getAccessRole())activities.record(actor.getOrganization(),ActivityAction.ROLE_CHANGED,"Member",m.getId(),oldRole+" -> "+m.getAccessRole());if(!Objects.equals(oldTeam,m.getTeam()==null?null:m.getTeam().getId()))activities.record(actor.getOrganization(),ActivityAction.MEMBER_MOVED_TEAM,"Member",m.getId(),m.getName());if(!Objects.equals(oldManager,m.getManager()==null?null:m.getManager().getId()))activities.record(actor.getOrganization(),ActivityAction.MANAGER_CHANGED,"Member",m.getId(),m.getName());if(m.getUser()!=null&&(!Objects.equals(oldManager,m.getManager()==null?null:m.getManager().getId())||!Objects.equals(oldTeam,m.getTeam()==null?null:m.getTeam().getId())||!Objects.equals(oldPosition,m.getPosition()==null?null:m.getPosition().getId())))notifications.create(m.getUser(),m.getOrganization(),"MEMBER_UPDATED","Your organization profile changed","Team, position or reporting information was updated.","/members");return Mappers.member(m);}
 @Transactional public void delete(Long oid,Long id){Member actor=access.requireAdmin(oid);Member m=require(oid,id);if(m.getAccessRole()==AccessRole.OWNER)throw new BusinessException("The organization owner cannot be removed");m.setStatus(RecordStatus.INACTIVE);activities.record(actor.getOrganization(),ActivityAction.MEMBER_REMOVED,"Member",m.getId(),m.getName());}
 Member require(Long oid,Long id){return members.findByIdAndOrganizationId(id,oid).orElseThrow(()->new ResourceNotFoundException("Member not found"));}
 private void apply(Member m,Request r,Long oid){m.setName(r.name().trim());m.setEmail(blank(r.email()));m.setStatus(r.status()==null?m.getStatus():r.status());m.setJoinedAt(r.joinedAt()==null?m.getJoinedAt():r.joinedAt());m.setLocation(blank(r.location()));m.setPhone(blank(r.phone()));m.setBio(blank(r.bio()));m.setAvatarUrl(blank(r.avatarUrl()));m.setPosition(r.positionId()==null?null:positions.findByIdAndOrganizationId(r.positionId(),oid).orElseThrow(()->new ResourceNotFoundException("Position not found")));m.setTeam(r.teamId()==null?null:teams.findByIdAndOrganizationId(r.teamId(),oid).orElseThrow(()->new ResourceNotFoundException("Team not found")));Member manager=r.managerId()==null?null:require(oid,r.managerId());validateManager(m,manager);m.setManager(manager);}
 private void validateManager(Member member,Member manager){if(manager==null)return;if(member.getId()!=null&&member.getId().equals(manager.getId()))throw new HierarchyCycleException("A member cannot manage themselves");Set<Long> seen=new HashSet<>();Member cursor=manager;while(cursor!=null){if(cursor.getId()!=null&&!seen.add(cursor.getId()))throw new HierarchyCycleException("Hierarchy already contains a cycle");if(member.getId()!=null&&member.getId().equals(cursor.getId()))throw new HierarchyCycleException("Manager assignment would create a hierarchy cycle");cursor=cursor.getManager();}}
 private void ensureManagerScope(Member actor,Member target){if(actor.getAccessRole()!=AccessRole.MANAGER)return;boolean direct=target.getManager()!=null&&target.getManager().getId().equals(actor.getId());boolean sameTeam=actor.getTeam()!=null&&target.getTeam()!=null&&actor.getTeam().getId().equals(target.getTeam().getId());if(!direct&&!sameTeam&&!actor.getId().equals(target.getId()))throw new ForbiddenException("Managers can only update their team or direct reports");} private AccessRole allowedRole(Member actor,AccessRole requested){if(requested==AccessRole.OWNER)throw new ForbiddenException("Owner access cannot be granted through member management");return requested;} private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
}
