package com.companages.service;
import com.companages.dto.OrganizationDtos.*; import com.companages.entity.*; import com.companages.exception.ResourceNotFoundException; import com.companages.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.List;
@Service public class OrganizationService {
 private final OrganizationRepository organizations; private final MemberRepository members; private final CurrentUserService current; private final OrganizationAccessService access; private final ActivityService activities;
 public OrganizationService(OrganizationRepository o,MemberRepository m,CurrentUserService c,OrganizationAccessService a,ActivityService l){organizations=o;members=m;current=c;access=a;activities=l;}
 @Transactional public Response create(CreateRequest r){User user=current.get();Organization o=new Organization();apply(o,r.name(),r.description(),r.logoUrl(),r.website(),r.phone(),r.email(),r.address());o.setOwner(user);o=organizations.save(o);Member membership=new Member();membership.setName(user.getName());membership.setEmail(user.getEmail());membership.setUser(user);membership.setOrganization(o);membership.setAccessRole(AccessRole.OWNER);membership.setStatus(RecordStatus.ACTIVE);membership.setJoinedAt(LocalDate.now());members.save(membership);activities.record(o,ActivityAction.ORGANIZATION_CREATED,"Organization",o.getId(),o.getName());return Mappers.organization(o,AccessRole.OWNER);}
 @Transactional(readOnly=true) public List<Response> list(){Long userId=current.get().getId();return organizations.findAllForUser(userId).stream().map(o->Mappers.organization(o,members.findByOrganizationIdAndUserId(o.getId(),userId).orElseThrow().getAccessRole())).toList();}
 @Transactional(readOnly=true) public Response get(Long id){Member m=access.requireMember(id);return Mappers.organization(m.getOrganization(),m.getAccessRole());}
 @Transactional public Response update(Long id,UpdateRequest r){Member membership=access.requireAdmin(id);Organization o=membership.getOrganization();apply(o,r.name(),r.description(),r.logoUrl(),r.website(),r.phone(),r.email(),r.address());activities.record(o,ActivityAction.ORGANIZATION_UPDATED,"Organization",o.getId(),o.getName());return Mappers.organization(o,membership.getAccessRole());}
 @Transactional public void archive(Long id){Organization o=access.requireOwner(id).getOrganization();o.setStatus(RecordStatus.ARCHIVED);activities.record(o,ActivityAction.ORGANIZATION_ARCHIVED,"Organization",o.getId(),o.getName());}
 @Transactional public void restore(Long id){Organization o=access.requireOwner(id).getOrganization();o.setStatus(RecordStatus.ACTIVE);activities.record(o,ActivityAction.ORGANIZATION_RESTORED,"Organization",o.getId(),o.getName());}
 @Transactional public void delete(Long id){archive(id);}
 @Transactional(readOnly=true) public Organization require(Long id){access.requireMember(id);return organizations.findById(id).orElseThrow(()->new ResourceNotFoundException("Organization not found"));}
 private void apply(Organization o,String name,String description,String logo,String website,String phone,String email,String address){o.setName(name.trim());o.setDescription(description);o.setLogoUrl(logo);o.setWebsite(website);o.setPhone(phone);o.setEmail(email);o.setAddress(address);}
}
