package com.companages.service;
import com.companages.dto.*; import com.companages.dto.TeamDtos.*; import com.companages.entity.*; import com.companages.exception.ResourceNotFoundException; import com.companages.repository.*; import jakarta.persistence.criteria.Predicate; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.ArrayList;
@Service public class TeamService { private final TeamRepository teams; private final MemberRepository members; private final OrganizationAccessService access; private final ActivityService activities; private final NotificationService notifications; public TeamService(TeamRepository t,MemberRepository m,OrganizationAccessService a,ActivityService l,NotificationService n){teams=t;members=m;access=a;activities=l;notifications=n;}
 @Transactional public Response create(Long oid,Request r){Member actor=access.requireManager(oid);Team t=new Team();t.setOrganization(actor.getOrganization());apply(t,r,oid);t=teams.save(t);activities.record(actor.getOrganization(),ActivityAction.TEAM_CREATED,"Team",t.getId(),t.getName());if(actor.getUser()!=null)notifications.create(actor.getUser(),actor.getOrganization(),"TEAM_CREATED","Team created",t.getName()+" was added to the organization.","/teams");return map(t);}
 @Transactional(readOnly=true) public PageResponse<Response> list(Long oid,String search,RecordStatus status,Pageable pageable){access.requireMember(oid);String term=blank(search);Specification<Team> spec=(root,query,cb)->{var predicates=new ArrayList<Predicate>();predicates.add(cb.equal(root.get("organization").get("id"),oid));if(term!=null)predicates.add(cb.like(cb.lower(root.get("name")),"%"+term.toLowerCase()+"%"));if(status!=null)predicates.add(cb.equal(root.get("status"),status));return cb.and(predicates.toArray(Predicate[]::new));};return PageResponse.from(teams.findAll(spec,pageable),this::map);}
 @Transactional(readOnly=true) public Response get(Long oid,Long id){access.requireMember(oid);return map(require(oid,id));}
 @Transactional public Response update(Long oid,Long id,Request r){Member actor=access.requireManager(oid);Team t=require(oid,id);if(actor.getAccessRole()==AccessRole.MANAGER&&actor.getTeam()!=null&&!actor.getTeam().getId().equals(t.getId()))throw new com.companages.exception.ForbiddenException("Managers can only update their own team");apply(t,r,oid);activities.record(actor.getOrganization(),ActivityAction.TEAM_UPDATED,"Team",t.getId(),t.getName());return map(t);}
 @Transactional public void archive(Long oid,Long id){Member actor=access.requireAdmin(oid);Team t=require(oid,id);t.setStatus(RecordStatus.ARCHIVED);activities.record(actor.getOrganization(),ActivityAction.TEAM_UPDATED,"Team",t.getId(),"Archived "+t.getName());} @Transactional public void restore(Long oid,Long id){Member actor=access.requireAdmin(oid);Team t=require(oid,id);t.setStatus(RecordStatus.ACTIVE);activities.record(actor.getOrganization(),ActivityAction.TEAM_UPDATED,"Team",t.getId(),"Restored "+t.getName());} Team require(Long oid,Long id){return teams.findByIdAndOrganizationId(id,oid).orElseThrow(()->new ResourceNotFoundException("Team not found"));}
 private void apply(Team t,Request r,Long oid){t.setName(r.name().trim());t.setDescription(r.description());t.setLead(r.leadMemberId()==null?null:members.findByIdAndOrganizationId(r.leadMemberId(),oid).orElseThrow(()->new ResourceNotFoundException("Team lead not found")));} private Response map(Team t){return Mappers.team(t,members.countByTeamId(t.getId()));} private String blank(String v){return v==null||v.isBlank()?null:v;}
}
