package com.companages.entity;
public enum ActivityAction { ORGANIZATION_CREATED, ORGANIZATION_UPDATED, ORGANIZATION_ARCHIVED, ORGANIZATION_RESTORED, MEMBER_ADDED, MEMBER_REMOVED, MEMBER_UPDATED, ROLE_CHANGED, JOB_POSITION_CHANGED, TEAM_CREATED, TEAM_UPDATED, MEMBER_MOVED_TEAM, MANAGER_CHANGED, INVITATION_SENT, INVITATION_ACCEPTED }
