package com.companages;

import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Transactional
class AuthAndOwnershipIntegrationTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json;
 @Test void registrationLoginAndProtectedEndpointWork() throws Exception {String token=register("Ana","ana@example.com");mvc.perform(get("/api/dashboard")).andExpect(status().isUnauthorized());mvc.perform(get("/api/auth/me").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.email").value("ana@example.com"));mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"ana@example.com\",\"password\":\"password123\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.token").isNotEmpty());}
 @Test void duplicateEmailIsRejected() throws Exception {register("Ana","duplicate@example.com");mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Other\",\"email\":\"duplicate@example.com\",\"password\":\"password123\"}")).andExpect(status().isConflict());}
 @Test void invalidLoginIsRejected() throws Exception {register("Ana","login@example.com");mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"login@example.com\",\"password\":\"wrong-password\"}")).andExpect(status().isUnauthorized());}
 @Test void oneUserCannotAccessAnotherUsersOrganization() throws Exception {String owner=register("Owner","owner@example.com");long id=createOrganization(owner,"Secret team");String stranger=register("Stranger","stranger@example.com");mvc.perform(get("/api/organizations/"+id).header("Authorization","Bearer "+stranger)).andExpect(status().isNotFound());mvc.perform(get("/api/organizations/"+id).header("Authorization","Bearer "+owner)).andExpect(status().isOk()).andExpect(jsonPath("$.name").value("Secret team"));}
 @Test void assignmentRequiresResourcesFromTheSameOrganization() throws Exception {String token=register("Manager","manager@example.com");long first=createOrganization(token,"First");long second=createOrganization(token,"Second");long member=idOf(mvc.perform(post("/api/organizations/"+first+"/members").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Alex\",\"email\":\"alex@example.com\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());long position=idOf(mvc.perform(post("/api/organizations/"+second+"/positions").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Developer\",\"description\":\"Builds products\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());mvc.perform(post("/api/organizations/"+first+"/assignments").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"memberId\":"+member+",\"positionId\":"+position+"}")).andExpect(status().isNotFound());}
 @Test void teamResourcesCompleteTheirLifecycle() throws Exception {String token=register("Lead","lead@example.com");long org=createOrganization(token,"Product");long member=idOf(mvc.perform(post("/api/organizations/"+org+"/members").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Alex\",\"email\":\"alex@example.com\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());mvc.perform(put("/api/organizations/"+org+"/members/"+member).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Alex Silva\",\"email\":\"alex@example.com\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.name").value("Alex Silva"));long position=idOf(mvc.perform(post("/api/organizations/"+org+"/positions").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Developer\",\"description\":\"Builds products\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());long assignment=idOf(mvc.perform(post("/api/organizations/"+org+"/assignments").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"memberId\":"+member+",\"positionId\":"+position+"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.member.id").value(member)).andReturn().getResponse().getContentAsString());mvc.perform(get("/api/organizations/"+org+"/assignments").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$[0].position.name").value("Developer"));mvc.perform(delete("/api/organizations/"+org+"/assignments/"+assignment).header("Authorization","Bearer "+token)).andExpect(status().isNoContent());mvc.perform(delete("/api/organizations/"+org+"/members/"+member).header("Authorization","Bearer "+token)).andExpect(status().isNoContent());mvc.perform(delete("/api/organizations/"+org+"/positions/"+position).header("Authorization","Bearer "+token)).andExpect(status().isNoContent());}
 private String register(String name,String email)throws Exception{String body=mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\""+name+"\",\"email\":\""+email+"\",\"password\":\"password123\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.user.password").doesNotExist()).andReturn().getResponse().getContentAsString();return json.readTree(body).get("token").asText();}
 private long createOrganization(String token,String name)throws Exception{return idOf(mvc.perform(post("/api/organizations").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\""+name+"\",\"description\":\"Description\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());}
 private long idOf(String body)throws Exception{return json.readTree(body).get("id").asLong();}
}
