package com.companages;

import com.companages.entity.*;
import com.companages.repository.*;
import com.companages.service.MailService;
import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import static org.hamcrest.Matchers.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Transactional
class SaasFeaturesIntegrationTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired UserRepository users; @Autowired OrganizationRepository organizations; @Autowired MemberRepository members; @MockitoBean MailService mail;

 @Test void refreshTokensRotateAndCannotBeReused() throws Exception {JsonNode auth=register("Refresh User","refresh@example.com");String refresh=auth.get("refreshToken").asText();String body=mvc.perform(post("/api/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+refresh+"\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.accessToken").isNotEmpty()).andExpect(jsonPath("$.refreshToken",not(refresh))).andReturn().getResponse().getContentAsString();mvc.perform(post("/api/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+refresh+"\"}")).andExpect(status().isBadRequest());org.junit.jupiter.api.Assertions.assertFalse(json.readTree(body).get("refreshToken").asText().isBlank());}

 @Test void regularMemberCannotManageTeamsAndTenantIsolationHidesOtherOrganizations() throws Exception {JsonNode ownerAuth=register("Owner","rbac-owner@example.com");long org=createOrganization(ownerAuth,"RBAC Org");JsonNode memberAuth=register("Member","rbac-member@example.com");addMembership(org,"rbac-member@example.com",AccessRole.MEMBER);String memberToken=memberAuth.get("accessToken").asText();mvc.perform(post("/api/organizations/"+org+"/teams").header("Authorization","Bearer "+memberToken).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Forbidden team\"}")).andExpect(status().isForbidden());JsonNode strangerAuth=register("Stranger","isolated@example.com");mvc.perform(get("/api/organizations/"+org).header("Authorization","Bearer "+strangerAuth.get("accessToken").asText())).andExpect(status().isNotFound());}

 @Test void teamsCanBeCreatedUpdatedAndArchived() throws Exception {JsonNode auth=register("Team Owner","team-owner@example.com");long org=createOrganization(auth,"Teams Org");String token=auth.get("accessToken").asText();long team=idOf(mvc.perform(post("/api/organizations/"+org+"/teams").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Product\",\"description\":\"Builds products\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("ACTIVE")).andReturn().getResponse().getContentAsString());mvc.perform(put("/api/organizations/"+org+"/teams/"+team).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Product Design\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.name").value("Product Design"));mvc.perform(delete("/api/organizations/"+org+"/teams/"+team).header("Authorization","Bearer "+token)).andExpect(status().isNoContent());}

 @Test void hierarchyRejectsSelfManagementAndCycles() throws Exception {JsonNode auth=register("Hierarchy Owner","hierarchy@example.com");long org=createOrganization(auth,"Hierarchy Org");String token=auth.get("accessToken").asText();long first=createMember(org,token,"First");long second=createMember(org,token,"Second");mvc.perform(put("/api/organizations/"+org+"/members/"+first).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"First\",\"managerId\":"+first+"}")).andExpect(status().isConflict());mvc.perform(put("/api/organizations/"+org+"/members/"+first).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"First\",\"managerId\":"+second+"}")).andExpect(status().isOk());mvc.perform(put("/api/organizations/"+org+"/members/"+second).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Second\",\"managerId\":"+first+"}")).andExpect(status().isConflict());}

 @Test void invitationCanBeSentAndAcceptedByMatchingAccount() throws Exception {JsonNode owner=register("Invite Owner","invite-owner@example.com");JsonNode invited=register("Invited User","invited@example.com");long org=createOrganization(owner,"Invitation Org");mvc.perform(post("/api/organizations/"+org+"/invitations").header("Authorization","Bearer "+owner.get("accessToken").asText()).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"invited@example.com\",\"role\":\"MEMBER\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("PENDING"));ArgumentCaptor<String> body=ArgumentCaptor.forClass(String.class);verify(mail).send(eq("invited@example.com"),anyString(),body.capture());String raw=body.getValue().substring(body.getValue().indexOf("token=")+6);mvc.perform(post("/api/invitations/accept").header("Authorization","Bearer "+invited.get("accessToken").asText()).contentType(MediaType.APPLICATION_JSON).content("{\"token\":\""+raw+"\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ACCEPTED"));mvc.perform(get("/api/organizations/"+org).header("Authorization","Bearer "+invited.get("accessToken").asText())).andExpect(status().isOk());}

 @Test void postgresSafeSearchesExposeSavedDataActivityAndNotifications() throws Exception {JsonNode auth=register("Search Owner","search-owner@example.com");String token=auth.get("accessToken").asText();long org=createOrganization(auth,"Search Org");mvc.perform(post("/api/organizations/"+org+"/positions").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Engineer\",\"level\":3}")).andExpect(status().isCreated()).andExpect(jsonPath("$.name").value("Engineer"));mvc.perform(get("/api/organizations/"+org+"/positions/search").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].name").value("Engineer"));mvc.perform(get("/api/organizations/"+org+"/members/search").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].name").value("Search Owner"));mvc.perform(get("/api/organizations/"+org+"/activities").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.content",not(empty())));mvc.perform(get("/api/notifications").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].type").value("POSITION_CREATED"));}

 private JsonNode register(String name,String email)throws Exception{return json.readTree(mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\""+name+"\",\"email\":\""+email+"\",\"password\":\"password123\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());}
 private long createOrganization(JsonNode auth,String name)throws Exception{return idOf(mvc.perform(post("/api/organizations").header("Authorization","Bearer "+auth.get("accessToken").asText()).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\""+name+"\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());}
 private long createMember(long org,String token,String name)throws Exception{return idOf(mvc.perform(post("/api/organizations/"+org+"/members").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\""+name+"\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());}
 private void addMembership(long orgId,String email,AccessRole role){Organization org=organizations.findById(orgId).orElseThrow();User user=users.findByEmailIgnoreCase(email).orElseThrow();Member m=new Member();m.setOrganization(org);m.setUser(user);m.setName(user.getName());m.setEmail(user.getEmail());m.setAccessRole(role);members.save(m);}
 private long idOf(String body)throws Exception{return json.readTree(body).get("id").asLong();}
}
